# Generated by Django 6.0.4 on 2026-05-05 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_image_url_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='deal_end_hour',
            field=models.IntegerField(default=23, help_text='Hour (0-23) when deal ends'),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_start_hour',
            field=models.IntegerField(default=0, help_text='Hour (0-23) when deal starts'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_daily_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
