# Generated by Django 6.0.4 on 2026-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_product_deal_end_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_daily_deal',
            new_name='is_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_end_hour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_start_hour',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
